name: Login ghcr.io

on:
  push:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        count: [0,1,2,3,4,5,6,7]      

    steps:
      - run: docker login ghcr.io -u token -p ${{ github.token }}
